"""empty message

Revision ID: 0692a8a085a9
Revises: 5545996b6fb7
Create Date: 2020-11-02 15:58:03.926978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0692a8a085a9'
down_revision = '5545996b6fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('create_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('products', sa.Column('update_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'update_at')
    op.drop_column('products', 'create_at')
    # ### end Alembic commands ###
