"""empty message

Revision ID: 12ae8b027e6c
Revises: 2e030aacc1ca
Create Date: 2020-11-01 23:16:27.265171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ae8b027e6c'
down_revision = '2e030aacc1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aboutus',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('des', sa.String(length=255), nullable=True),
    sa.Column('des2', sa.String(length=255), nullable=True),
    sa.Column('des3', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aboutus')
    # ### end Alembic commands ###
