"""empty message

Revision ID: 1edbd0c9fd40
Revises: 997a84636b2b
Create Date: 2020-11-01 20:09:45.061843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edbd0c9fd40'
down_revision = '997a84636b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('des', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_table('products')
    # ### end Alembic commands ###
