"""empty message

Revision ID: 3d4f5207777a
Revises: 12ae8b027e6c
Create Date: 2020-11-02 13:30:29.363982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4f5207777a'
down_revision = '12ae8b027e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('update_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_at')
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###
