"""empty message

Revision ID: 693f6a3af72e
Revises: 1edbd0c9fd40
Create Date: 2020-11-01 20:52:43.716510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693f6a3af72e'
down_revision = '1edbd0c9fd40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('des', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
