"""empty message

Revision ID: 997a84636b2b
Revises: bf1e3a48ea16
Create Date: 2020-11-01 16:34:45.131285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997a84636b2b'
down_revision = 'bf1e3a48ea16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('phonenumber', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phonenumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
