"""empty message

Revision ID: c40f1d8faa7d
Revises: 91943d266b81
Create Date: 2020-11-03 11:33:59.262808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40f1d8faa7d'
down_revision = '91943d266b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Addcart', sa.Column('phone', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Addcart', 'phone')
    # ### end Alembic commands ###
